### ISSUE TITLE
Adicionar micronação - Lancastria

### ISSUE THREAD

**Issue by IgorLancastre** [lonedevsoftware/AlmanaqueMicronacional#18]
O nome comum da micronação; Lancastria
O nome oficial da micronação; Estado Livre da Lancastria
Sua data de fundação; 13/10/2017
Sua forma de governo; Monarquia Constitucional
Seus chefes de Estado e de Governo; Igor Lancastre, Chefe de Estado e de Governo.
Website; www.lancastriagov.wordpress.com
Redes sociais (Facebook, Twitter); facebook.com/lancastriagov
Praça Pública (fórum, lista, etc.) lancastria.boards.net

**Comment by joaosantana** [comment]
:heartbeat:  Obrigado por sua contribuição. Solicitações adicionais serão feitas nesta thread.

**Comment by joaosantana** [comment]
@IgorLancastre, peço que envie o brasão de armas e bandeira da Lancastria para o email almanaquemicronacional@outlook.com, para adicionar ao Almanaque.
